events {}

http {
  server {
    listen 80;

    # Landing page
    location / {
      proxy_pass http://landing-page-production.railway.internal;
      proxy_set_header Host $host;
    }

    # Accommodation
    location /rabit-delux-retreat/ {
      proxy_pass http://rabit-delux-retreat.railway.internal/rabit-delux-retreat/;
      proxy_set_header Host $host;
    }

  }
}
