events {}

http {
  server {
    listen 80;

    # Landing page
    location / {
      proxy_pass http://landing.INTERNAL:80;
      proxy_set_header Host $host;
    }

    # Example accommodation
    location /santa-monica-coastal/ {
      proxy_pass http://santa-monica-coastal.INTERNAL:80/santa-monica-coastal/;
      proxy_set_header Host $host;
    }

  }
}
