events {}

http {
  server {
    listen 80;

    # Landing page
    location / {
      proxy_pass http://landing-page-production.railway.internal:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Accommodation
    location /rabit-delux-retreat/ {
      proxy_pass http://rabit-delux-retreat-production.railway.internal:80/rabit-delux-retreat/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

  }
}
